name: TSC Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main

jobs:
  tsc-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'
      - name: Install Dependencies
        run: npm install
      - name: Run TSC Check
        run: npm run tsc
