name: Run Unit Tests on Multiple OS

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  run-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change Directory to API
        run: cd api

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  run-tests-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change Directory to API
        run: cd api

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  run-tests-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change Directory to API
        run: cd api

      - nam
